# This file is used to set the compile options for the project.
CXX                         :=  g++
CUDA_VER                    :=  12.4

# Opencv and Tensorrt installation directory
OPENCV_INSTALL_DIR          :=  /usr/local/include/opencv4
TENSORRT_INSTALL_DIR        :=  /home/suojinhui/TensorRT-10.5.0.18
LIBYUV_INSTALL_DIR          :=  /usr/local/libyuv

# Compile options
DEBUG                       :=  1
SHOW_WARNING                :=  0

# Compile applications
APP                         :=  trt-yolov10-app